"""
System-wide constants for the Inventory Management System.

This module defines all constant values used throughout the application
to avoid hard-coding and ensure consistency.
"""

# User Roles
ROLE_ADMIN = 'admin'
ROLE_INVENTORY_MANAGER = 'inventory_manager'
ROLE_WAREHOUSE_STAFF = 'warehouse_staff'
ROLE_VIEWER = 'viewer'

VALID_ROLES = [
    ROLE_ADMIN,
    ROLE_INVENTORY_MANAGER,
    ROLE_WAREHOUSE_STAFF,
    ROLE_VIEWER
]

# Receipt Statuses
RECEIPT_STATUS_DRAFT = 'draft'
RECEIPT_STATUS_WAITING = 'waiting'
RECEIPT_STATUS_READY = 'ready'
RECEIPT_STATUS_DONE = 'done'
RECEIPT_STATUS_CANCELLED = 'cancelled'

RECEIPT_STATUSES = [
    RECEIPT_STATUS_DRAFT,
    RECEIPT_STATUS_WAITING,
    RECEIPT_STATUS_READY,
    RECEIPT_STATUS_DONE,
    RECEIPT_STATUS_CANCELLED
]

RECEIPT_STATUS_FLOW = {
    RECEIPT_STATUS_DRAFT: [RECEIPT_STATUS_WAITING, RECEIPT_STATUS_CANCELLED],
    RECEIPT_STATUS_WAITING: [RECEIPT_STATUS_READY, RECEIPT_STATUS_CANCELLED],
    RECEIPT_STATUS_READY: [RECEIPT_STATUS_DONE, RECEIPT_STATUS_CANCELLED],
    RECEIPT_STATUS_DONE: [],
    RECEIPT_STATUS_CANCELLED: []
}

# Delivery Statuses
DELIVERY_STATUS_PICK = 'pick'
DELIVERY_STATUS_PACK = 'pack'
DELIVERY_STATUS_VALIDATE = 'validate'
DELIVERY_STATUS_SHIPPED = 'shipped'
DELIVERY_STATUS_CANCELLED = 'cancelled'

DELIVERY_STATUSES = [
    DELIVERY_STATUS_PICK,
    DELIVERY_STATUS_PACK,
    DELIVERY_STATUS_VALIDATE,
    DELIVERY_STATUS_SHIPPED,
    DELIVERY_STATUS_CANCELLED
]

DELIVERY_STATUS_FLOW = {
    DELIVERY_STATUS_PICK: [DELIVERY_STATUS_PACK, DELIVERY_STATUS_CANCELLED],
    DELIVERY_STATUS_PACK: [DELIVERY_STATUS_VALIDATE, DELIVERY_STATUS_CANCELLED],
    DELIVERY_STATUS_VALIDATE: [DELIVERY_STATUS_SHIPPED, DELIVERY_STATUS_CANCELLED],
    DELIVERY_STATUS_SHIPPED: [],
    DELIVERY_STATUS_CANCELLED: []
}

# Transfer Statuses
TRANSFER_STATUS_DRAFT = 'draft'
TRANSFER_STATUS_IN_TRANSIT = 'in_transit'
TRANSFER_STATUS_COMPLETED = 'completed'
TRANSFER_STATUS_CANCELLED = 'cancelled'

TRANSFER_STATUSES = [
    TRANSFER_STATUS_DRAFT,
    TRANSFER_STATUS_IN_TRANSIT,
    TRANSFER_STATUS_COMPLETED,
    TRANSFER_STATUS_CANCELLED
]

TRANSFER_STATUS_FLOW = {
    TRANSFER_STATUS_DRAFT: [TRANSFER_STATUS_IN_TRANSIT, TRANSFER_STATUS_CANCELLED],
    TRANSFER_STATUS_IN_TRANSIT: [TRANSFER_STATUS_COMPLETED, TRANSFER_STATUS_CANCELLED],
    TRANSFER_STATUS_COMPLETED: [],
    TRANSFER_STATUS_CANCELLED: []
}

# Adjustment Statuses
ADJUSTMENT_STATUS_DRAFT = 'draft'
ADJUSTMENT_STATUS_APPROVED = 'approved'
ADJUSTMENT_STATUS_CANCELLED = 'cancelled'

ADJUSTMENT_STATUSES = [
    ADJUSTMENT_STATUS_DRAFT,
    ADJUSTMENT_STATUS_APPROVED,
    ADJUSTMENT_STATUS_CANCELLED
]

ADJUSTMENT_STATUS_FLOW = {
    ADJUSTMENT_STATUS_DRAFT: [ADJUSTMENT_STATUS_APPROVED, ADJUSTMENT_STATUS_CANCELLED],
    ADJUSTMENT_STATUS_APPROVED: [],
    ADJUSTMENT_STATUS_CANCELLED: []
}

# Adjustment Types
ADJUSTMENT_TYPE_PHYSICAL_COUNT = 'physical_count'
ADJUSTMENT_TYPE_DAMAGE = 'damage'
ADJUSTMENT_TYPE_LOSS = 'loss'
ADJUSTMENT_TYPE_FOUND = 'found'

ADJUSTMENT_TYPES = [
    ADJUSTMENT_TYPE_PHYSICAL_COUNT,
    ADJUSTMENT_TYPE_DAMAGE,
    ADJUSTMENT_TYPE_LOSS,
    ADJUSTMENT_TYPE_FOUND
]

# Stock Ledger Transaction Types
TRANSACTION_TYPE_RECEIPT = 'receipt'
TRANSACTION_TYPE_DELIVERY = 'delivery'
TRANSACTION_TYPE_TRANSFER_IN = 'transfer_in'
TRANSACTION_TYPE_TRANSFER_OUT = 'transfer_out'
TRANSACTION_TYPE_ADJUSTMENT = 'adjustment'

TRANSACTION_TYPES = [
    TRANSACTION_TYPE_RECEIPT,
    TRANSACTION_TYPE_DELIVERY,
    TRANSACTION_TYPE_TRANSFER_IN,
    TRANSACTION_TYPE_TRANSFER_OUT,
    TRANSACTION_TYPE_ADJUSTMENT
]

# Product Units
UNIT_PIECES = 'pcs'
UNIT_KILOGRAMS = 'kg'
UNIT_GRAMS = 'g'
UNIT_LITERS = 'l'
UNIT_MILLILITERS = 'ml'
UNIT_METERS = 'm'
UNIT_BOXES = 'box'

VALID_UNITS = [
    UNIT_PIECES,
    UNIT_KILOGRAMS,
    UNIT_GRAMS,
    UNIT_LITERS,
    UNIT_MILLILITERS,
    UNIT_METERS,
    UNIT_BOXES
]

# Pagination
DEFAULT_PAGE = 1
MAX_ITEMS_PER_PAGE = 100

# Date Formats
DATE_FORMAT = '%Y-%m-%d'
DATETIME_FORMAT = '%Y-%m-%d %H:%M:%S'
DISPLAY_DATE_FORMAT = '%d %b %Y'
DISPLAY_DATETIME_FORMAT = '%d %b %Y %H:%M'
